import UIKit
import Foundation
//import Alamofire
class WLinks {
    
    static let baseUrl = "https://logicaltest.website/Anju/Boricua/Api/"
    
    static let baseImg = "https://logicaltest.website/Anju/Boricua/assets/bori_images/category/"
    
    static let baseImgListing = "https://logicaltest.website/Anju/Boricua/assets/bori_images/listing/"

    static let baseImgRating = "https://logicaltest.website/Anju/Boricua/assets/bori_images/rating/"
   
    static let baseImgEvtn = "https://logicaltest.website/Anju/Boricua/assets/bori_images/event/"
    
    static let baseImgUsers = "https://logicaltest.website/Anju/Boricua/assets/bori_images/users/"

    static let ws_Login = WLinks.baseUrl + "login"
    static let ws_SignUp = WLinks.baseUrl + "user_signup"
    static let ws_Logout = WLinks.baseUrl + "logout"
    static let ws_category_list = WLinks.baseUrl + "category_list"
    static let ws_get_country  = WLinks.baseUrl + "get_country"
    static let ws_update_user_country  = WLinks.baseUrl + "update_user_country"
    static let ws_get_faq  = WLinks.baseUrl + "get_faq"
    static let ws_get_about_us  = WLinks.baseUrl + "get_about_us"
    static let ws_get_privacy_policy  = WLinks.baseUrl + "get_privacy_policy"
    static let ws_get_terms_condtion  = WLinks.baseUrl + "get_terms_condtion"
    static let ws_get_states  = WLinks.baseUrl + "get_states"
    static let ws_mix_category_list  = WLinks.baseUrl + "mix_category_list"
    static let ws_vendor_signup  = WLinks.baseUrl + "vendor_signup"
    static let ws_get_user_vend_profile  = WLinks.baseUrl + "get_user_vend_profile"
    static let ws_add_vendor_listing  = WLinks.baseUrl + "add_vendor_listing"
    static let ws_get_vendor_listing  = WLinks.baseUrl + "get_vendor_listing"
    static let ws_get_user_profile  = WLinks.baseUrl + "get_user_profile"
    static let ws_update_user_profile  = WLinks.baseUrl + "update_user_profile"
    static let ws_get_vendor_profile  = WLinks.baseUrl + "get_vendor_profile"
    static let ws_vendor_update_profile  = WLinks.baseUrl + "vendor_update_profile"
    static let ws_sub_category_list  = WLinks.baseUrl + "sub_category_list"
    static let ws_get_banner  = WLinks.baseUrl + "get_banner"
    static let ws_get_home_listing  = WLinks.baseUrl + "get_home_listing"
    static let ws_delete_listing_images  = WLinks.baseUrl + "delete_listing_images"
    static let ws_delete_listing_menu  = WLinks.baseUrl + "delete_listing_menu"
    static let ws_add_review  = WLinks.baseUrl + "add_review"
    static let ws_get_listing_details  = WLinks.baseUrl + "get_listing_details"
    static let ws_add_more_listing_menu  = WLinks.baseUrl + "add_more_listing_menu"
    static let ws_add_more_listing_images  = WLinks.baseUrl + "add_more_listing_images"
    static let ws_favourite_unfavourite_listing  = WLinks.baseUrl + "favourite_unfavourite_listing"
    static let ws_get_favourite_list  = WLinks.baseUrl + "get_favourite_list"
    static let ws_get_home_addres_cate_fltr  = WLinks.baseUrl + "get_home_addres_cate_fltr"
    static let ws_change_password  = WLinks.baseUrl + "change_password"
    static let ws_get_help_center  = WLinks.baseUrl + "get_help_center"
    static let ws_listing_call_website_click  = WLinks.baseUrl + "listing_call_website_click"
    static let ws_get_listing_count  = WLinks.baseUrl + "get_listing_count"
    static let ws_update_business_name_logo  = WLinks.baseUrl + "update_business_name_logo"
    static let ws_get_listing_rating_list  = WLinks.baseUrl + "get_listing_rating_list"
    static let ws_get_vendor_subcatelist  = WLinks.baseUrl + "get_vendor_subcatelist"
    static let ws_update_vendor_list_subcate  = WLinks.baseUrl + "update_vendor_list_subcate"
    static let ws_Google_Login  = WLinks.baseUrl + "Google_Login"
    static let ws_get_deal_of_the_day  = WLinks.baseUrl + "get_deal_of_the_day"
   
    static let ws_add_listing_availability  = WLinks.baseUrl + "add_listing_availability"
    
    static let ws_get_listing_availability  = WLinks.baseUrl + "get_listing_availability"
    static let ws_get_check_in_uncheck  = WLinks.baseUrl + "get_check_in_uncheck"
    static let ws_update_check_in_listing  = WLinks.baseUrl + "update_check_in_listing"
    static let ws_get_review_list  = WLinks.baseUrl + "get_review_list"
    static let ws_get_check_in_listing  = WLinks.baseUrl + "get_check_in_listing"
    static let ws_get_event  = WLinks.baseUrl + "get_event"
    static let ws_get_les_presento  = WLinks.baseUrl + "get_les_presento"
    static let ws_les_presento_details  = WLinks.baseUrl + "les_presento_details"
    static let ws_get_volunteering  = WLinks.baseUrl + "get_volunteering"
    static let ws_volunteering_details  = WLinks.baseUrl + "volunteering_details"
    static let ws_get_job_opportunity  = WLinks.baseUrl + "get_job_opportunity"
    static let ws_job_opportunity_details  = WLinks.baseUrl + "job_opportunity_details"
    static let ws_get_educational  = WLinks.baseUrl + "get_educational"
    static let ws_event_details  = WLinks.baseUrl + "event_details"
    static let ws_educational_details  = WLinks.baseUrl + "educational_details"
    static let ws_get_home_subcate_fltr  = WLinks.baseUrl + "get_home_subcate_fltr"
    static let ws_forget_password  = WLinks.baseUrl + "forget_password"
    static let ws_get_listing_usercall  = WLinks.baseUrl + "get_listing_usercall"
    static let ws_subscription_purchased  = WLinks.baseUrl + "subscription_purchased"
    static let ws_get_listing_rating_comment  = WLinks.baseUrl + "get_listing_rating_comment"
    static let ws_rating_comment_by_vendor  = WLinks.baseUrl + "rating_comment_by_vendor"
    static let ws_sub_event_list  = WLinks.baseUrl + "sub_event_list"
    static let ws_event_list  = WLinks.baseUrl + "event_list"
    static let ws_get_chat_admin  = WLinks.baseUrl + "get_chat_admin"
    static let ws_chat_admin_user  = WLinks.baseUrl + "chat_admin_user"
    static let ws_Apple_Login  = WLinks.baseUrl + "Apple_Login"
    static let ws_get_sabias  = WLinks.baseUrl + "get_sabias"
    static let ws_sabias_details  = WLinks.baseUrl + "sabias_details"
    static let ws_get_vacation  = WLinks.baseUrl + "get_vacation"
    static let ws_vacation_details  = WLinks.baseUrl + "vacation_details"
    static let ws_notification_vendorside  = WLinks.baseUrl + "notification_vendorside"
    static let ws_youtube_podcast  = WLinks.baseUrl + "youtube_podcast"
    static let ws_update_license_language_qualifications  = WLinks.baseUrl + "update_license_language_qualifications"
    static let ws_get_stay_pr  = WLinks.baseUrl + "get_stay_pr"
    static let ws_get_eat_pr  = WLinks.baseUrl + "get_eat_pr"
    static let ws_get_event_pr  = WLinks.baseUrl + "get_event_pr"
    static let ws_puchased_plan_history  = WLinks.baseUrl + "puchased_plan_history"
    static let ws_contact_us  = WLinks.baseUrl + "contact_us"
   
 }


class WSConstantt{
    static let alertTitle = "Boricua App!"
    static let profile_picture = "profile_picture"
    static let group_id = "group_id"
    static let access_token = "access_token"
    static let user_type = "user_type"
    static let device_token = "device_token"
    static let device_type = "device_type"
    static let chat_already_started = "chat_already_started"
    static let email = "email"
    static let type = "type"
    static let full_name = "full_name"
    static let password = "password"
    static let contact = "contact"
    static let profile_pic = "profile_pic"
    static let shop_name = "shop_name"
    static let static_key = "static_key"
    static let terms_conditions = "terms_conditions"
    static let user_id = "user_id"
    static let user_ids = "user_ids"
    static let data = "data"
    static let message = "message"
    static let errorCode = "errorCode"
    static let id = "id"
    static let total_user = "total_user"
    static let pin_match = "pin_match"
    static let read_flag = "read_flag"
    static let first_name = "first_name"
    static let last_name = "last_name"
    static let country_id = "country_id"
    static let date_of_birth = "date_of_birth"

    //change pwd
    static let oldpassword = "old_password"
    static let newPassword = "new_password"
    //Service API
    
    static let category_id = "category_id"
    static let parent_type_id = "parent_type_id"
    static let category_name = "category_name"
    static let category_icon = "icon"
    static let logged_in_user_id = "logged_in_user_id"
    static let body = "body"
    static let year_of_experience = "year_of_experience"
    static let experience = "experience"
    static let location = "location"
    static let services = "services"
    static let trade_license = "trade_license"
    static let emirate_id = "emirate_id"
    static let is_provider = "is_provider"
    static let user_name = "user_name"
    static let social_id = "social_id"
    static let social_login_from = "social_login_from"
    static let parent_category_id = "parent_category_id"
    static let latitude = "latitude"
    static let longitude = "longitude"
    static let miles = "miles"
    static let search_string = "search_string"
    static let temp_id = "temp_id"
    static let session_id = "session_id"
    static let time = "time"
    static let date = "date"
    static let card_data = "card_data"
    static let is_leaf = "is_leaf"
    static let price = "price"
    static let total_rating = "total_rating"
    static let avg_rating = "avg_rating"
    static let Service_providername = "Service_providername"
    static let service_date = "service_date"
    static let service_time = "service_time"
    static let order_categories = "order_categories"
    static let user_location = "user_location"
    static let status = "status"
    static let provider_id = "provider_id"
    static let orderDetail = "orderDetail"
    static let car_type = "car_type"
    static let cartypeid = "carType_id"
    static let total_cost = "total_cost"
    static let order_id = "order_id"
    static let order_detail = "order_detail"
    static let cost = "cost"
    static let rating = "rating"
    static let review = "review"
    static let type_name = "type_name"
    static let type_id = "type_id"
    static let type_price = "type_price"
    static let icon = "icon"
    static let justParent = "justParent"
    //------------OrderDetal--------------
    static let order_category_id = "order_category_id"
    static let total_price = "total_price"
    static let category_name_arabic = "category_name_arabic"
    static let request_name = "request_name"
    static let payment_method = "payment_method"
    static let transaction_id = "transaction_id"
    static let transaction_status = "transaction_status"
    static let transaction_token = "transaction_token"
    static let shipping_address = "shipping_address"
    static let transaction_response = "transaction_response"
    //------------------------------------
    static let language = "language"
    //-----------Bank Detail--------
    static let bank_account_no = "bank_account_no"
    static let bank_name = "bank_name"
    static let topType = "topType"
    static let bank_user_name = "bank_user_name"
    static let bank_ifsc = "bank_ifsc"
    static let Categories = "Categories"
    static let servicesprice = "servicesprice"
    static let working_time = "working_time"
    static let service_id = "service_id"
    static let  package_detail =  "package_detail"
    static let Request_Name = "Request_Name"
    static let created_at = "created_at"
    static let receiver_user_id = "receiver_user_id"
    static let sender_user_id = "sender_user_id"
    static let request_id = "request_id"
    static let mobile_number = "mobile_number"
    static let quantity = "quantity"
    static let provider_shop_name = "provider_shop_name"
    static let content = "content"
    static let order_pin = "order_pin"
    static let confirmation = "confirmation"
    static let privacy_policy = "privacy_policy"
    static let Car_type = "Car_type"
    static let CategroyName = "CategroyName"
    static let car_type_id = "car_type_id"
    static let request_count = "request_count"
    static let chat_count = "chat_count"
    static let notifications_count = "notifications_count"
   
}

@available(iOS 13.0, *)
class AppConstantt {
    static let appdelegate = UIApplication.shared.delegate as! AppDelegate

}

class NotificatioNameTypee{
    static let ProviderPost = "ProviderPost"
    static let UserPost = "UserPost"
    static let order_submit = "order-submit"
    static let order_payment = "order-payment"
    static let service_confirmation = "service-confirmation"
    static let order_Status = "order-Status"
}

